### ISSUE TITLE
UTF-8 character in migration

### ISSUE THREAD

**Issue by 2e2a** [liqd/meinberlin-wagtail#28]
migrate with salt is failing do to some UTF-8 encoded character in PR #27

**Comment by xi** [comment]
This was probably caused by the migration from #27. We do not need that migration anymore because it has been executed manually on production and is not required for new installations (because it just updates a value that was also updated in `initial_content.json`). So we can simply remove that migration again.

So what is the best way to remove a migration? Actually removing it might confuse django, because the list of executed migrations is saved in the database. Maybe it is best change the migration so it simply does nothing.
